#!/bin/bash

if [ ! -d test ]; then
		mkdir ~/test
		echo "----------------------"
		echo "Test Directory Created"
		echo
fi

sudo touch ~/test/testFile ~/test/TestFile.txt ~/test/tEsTfIlE.html ~/test/TeStFiLe.c
echo
echo "------------------"
echo "Created Testfiles." 
echo