#!/bin/bash

if [[ ! -d test ]]; then
		mkdir ~/test
		echo "----------------------"
		echo "Test Directory Created"
		echo
fi

jf [[ -f ~/test/testFile ]]; then
		echo "------------------------"
		echo "Testfiles already exist."
		echo
else
		sudo touch ~/test/testFile ~/test/TestFile.txt ~/test/tEsTfIlE.html ~/test/TeStFiLe.c
		echo "------------------"
		echo "Created Testfiles." 
		echo
fi
